from math import *

versionprog = "7.0"
majdate = "16/12/2019"

print("")
print("Physique version ", versionprog)
print("")

while 1:

    print("")
    option = input("continuer (1) / infos (2) / quitter (3) : ")
    print("")

    if option == "1":
        print("")
        print("Type de volume à calculer :")
        print(" - Masse volumique (1)")
        print(" - Densités (2)")
        print(" - Concentration massique (3)")
        print(" - Lois des tensions (4)")
        print(" - Lois d'ohm (5)")
        print(" - Lois des tensions (en serie) (6)")
        print(" - Lois des tensions (en derivation) (7)")
        print(" - Lois des noeuds (8)")
        print(" - Masse atome par des constituant (9)")
        print(" - Notation atomique (10)")
        print(" - Configuration éléctronique (11)")
        print(" - Définition sur les mouvements (12)")
        print(" - Déscription d'un mouvements (13)")
        print(" - Formule d'un mouvements (14)")
        print(" - Caractérisitque du vecteur vitesse (15)")
        print(" - Poids (16)")
        print(" - Force support (17)")
        print(" - Force gravitationnelle (18)")
        print("")

        op = float(input("Qu'elle volume voulez vous calculez ? : "))

        if op == 1:
            print("")
            print("- Masse volumique :")
            print("p = m/V")
            print("m = p x V")
            print("V = m/p")
            print("")
        elif op == 2:
            print("")
            print("- Densités :")
            print("d = p/p eau")
            print("")
        elif op == 3:
            print("")
            print("- Concentration massique :")
            print("m = solutés")
            print("V = solution")
            print("Cm = m/V")
            print("m = Cm x V")
            print("V = m/Cm")
            print("")
        elif op == 4:
            print("")
            print("- Lois des tensions :")
            print("Uad - Uab - Uac = 0")
            print("")
        elif op == 5:
            print("")
            print("- Lois d'ohm :")
            print("U = R x I")
            print("I = U / R")
            print("R = U / I")
            print("")
        elif op == 6:
            print("")
            print("- Lois des tensions (en serie) :")
            print("Ug = U1 + U2")
            print("")
        elif op == 7:
            print("")
            print("- Lois des tensions (en derivation) :")
            print("Ug = U1 = U2")
            print("")
        elif op == 8:
            print("")
            print("- Lois des noeuds :")
            print("I1 + I2 = I3 + I4")
            print("")
        elif op == 9:
            print("")
            print("- Masse atome par des constituant (en kg) :")
            print("Proton : 1,6726x10**-27")
            print("Neutron : 1,6749x10**-27")
            print("Electron : 9,1094x10**-31")
            print("")
        elif op == 10:
            print("")
            print("- Notation atomique :")
            print("X : le symbole de l'atome considéré")
            print("A : le nombre de nucléons du noyau (nb de proton + neutrons)")
            print("Z : le numero atomique (nb de proton)")
            print("")
        elif op == 11:
            print("")
            print("- Configuration éléctronique :")
            print("1s2 2s2 2p6 3s2 3p6")
            print("")
        elif op == 12:
            print("")
            print("- Définition sur les mouvements :")
            print("Le système : c'est l’objet donc ton étudie le mouvements")
            print("Le référentiel : c'est un objet par rapport au quelle on étudie le mouvement du système")
            print("Référentiel terrestre : référentiel liés à la Terre : est immobile par rapport à la Terre")
            print("")
        elif op == 13:
            print("")
            print("- Déscription d'un mouvements :")
            print("Rectiligne : la trajectoire est une droite")
            print("Circulaire : la trajectoire est un cercle")
            print("Curviligne : la trajectoire est une courbe")
            print("Accéléré : la vitesse augmente")
            print("Ralenti : la vitesse diminue")
            print("Uniforme : la vitesse est constante")
            print("")
        elif op == 14:
            print("")
            print("- Formule d'un mouvements :")
            print("Vitesse moyenne (m/s) : v = d/t")
            print("Vitesse instant t (m/s) : v = (A + B)/t")
            print("")
        elif op == 15:
            print("")
            print("- Caractérisitque du vecteur vitesse :")
            print("O (origine)")
            print("D (direction)")
            print("S (sens)")
            print("V (vitesse)")
            print("")
        elif op == 16:
            print("")
            print("- Poids :")
            print("P = poid")
            print("m = masse (en kg)")
            print("g = pesenteur (en N/kg)")
            print("P = m x g")
            print("")
        elif op == 17:
            print("")
            print("- Force support :")
            print("D = perpendiculaire au support")
            print("S = du support vers le système")
            print("V = en N")
            print("")
        elif op == 18:
            print("")
            print("- Force gravitationnelle :")
            print("G = 6.67x10(-11)")
            print("Ma et Mb = masse de A et de B en kg)")
            print("Mb = masse de B en kg)")
            print("Fa/b = (G x Ma x Mb) / 2")
            print("")
        else:
            print("")
            print("erreur type de formule non trouvés")
            print("")
    elif option == "2":
        print("")
        print("Infos :")
        print(" - Nom : Physique")
        print(" - Auteur : Alan Bédrine")
        print(" - Version du programme :", versionprog)
        print(" - Dernière mise a jour :", majdate)
        print(" - Contribuer / source  : https://github.com/alanbedrine/PyTools")
        print("")
    elif option == "3":
        print("")
        print("Fin du programme")
        break